name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/pr-labeler-config.yml"
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        # only add names of Acryl Data team members here
        if: 
          ${{ 
            !contains(
              fromJson('[
                "skrydal",
                "siladitya2",
                "sgomezvillamor",
                "ngamanda",
                "HarveyLeo",
                "frsann",
                "bossenti",
                "nikolakasev",
                "PatrickfBraz",
                "cuong-pham",
                "sudhakarast",
                "tkdrahn",
                "rtekal",
                "sgm44"
              ]'), 
              github.actor
            ) 
          }}
        with:
          github_token: ${{ github.token }}
          labels: |
            datahub-community-champion
